### ISSUE TITLE
Navigation → Next button redirects to /page/NaN

### ISSUE THREAD

**Issue by jorisrenaud** [juneHQ/changelog#2]
**Case:** 
When clicking on "Next" button, I'm redirected to a 404 page → https://changelog.june.so/page/NaN

**Exploration:**
When charging [June changelog](https://changelog.june.so/), I got 2 errors present in the [screenshot](https://i.ibb.co/3fdbG3S/Screenshot-2023-02-17-at-14-04-13.png) below 👇

![Console error](https://i.ibb.co/3fdbG3S/Screenshot-2023-02-17-at-14-04-13.png)

I hope this will help 👍.

**Comment by ferrucc-io** [comment]
Thanks for reporting! Let me look into this!

**Comment by ferrucc-io** [comment]
Thanks for reporting just pushed a fix!
