### ISSUE TITLE
Design of mosaic hover effects

### ISSUE THREAD

**Issue by ferrucc-io** [juneHQ/changelog#24]
Feels a bit unpolished and hard to understand that it's clickable (maybe misses hover effects)

Would need a better design here for the interaction

**Comment by danieljune** [comment]
Tabs font-weight 
- Active tabs font-weight should be semi-bold
- Inactive tabs font-weight should be medium 
- [Design reference](https://www.figma.com/file/AdDX9S8y507EIUeEhkqZUa/Changelog-2.0?type=design&node-id=1%3A1722&mode=design&t=I1FGOVKBWi65AhkQ-1)

Update more photos pill (e.g. "+24") to:
- font-size: 12px;
- font-weight: semi-bold
- [Design reference](https://www.figma.com/file/AdDX9S8y507EIUeEhkqZUa/Changelog-2.0?type=design&node-id=2%3A2125&mode=design&t=I1FGOVKBWi65AhkQ-1) 

Tabs are not static on scroll so we don’t get the blur effect when the content scrolls behind it. 
- [Design reference](https://www.figma.com/file/AdDX9S8y507EIUeEhkqZUa/Changelog-2.0?type=design&node-id=2%3A2591&mode=design&t=I1FGOVKBWi65AhkQ-1)
- Inspiration reference: https://diagram.com 

In a changelog item, the back button doesn’t animate on hover: 
- [Design reference](https://www.figma.com/file/AdDX9S8y507EIUeEhkqZUa/Changelog-2.0?type=design&node-id=2%3A2488&mode=design&t=I1FGOVKBWi65AhkQ-1) 
- Inspiration reference: https://family.co/changelog/2023-05-25

What do we think about adding a subtle shadow on hover of the 1) weekly image 2) monthly mosaic 3) yearly mosaic?
- [Design reference](https://www.figma.com/file/AdDX9S8y507EIUeEhkqZUa/Changelog-2.0?type=design&node-id=81%3A649&mode=design&t=I1FGOVKBWi65AhkQ-1)

**Comment by danieljune** [comment]
To be consistent with june.so

Update 
- "Set up June" section 
- Footer font styles
- Login button font style in header (not pictured)

<img width="1512" alt="Screenshot 2023-06-26 at 13 00 07" src="https://github.com/juneHQ/changelog/assets/104089773/33da550d-a2a2-4180-acaa-4011791fe44e">

<img width="1512" alt="Screenshot 2023-06-26 at 12 59 48" src="https://github.com/juneHQ/changelog/assets/104089773/9a648a8e-d2b2-4d8b-9bc3-a90db596f7a7">

**Comment by danieljune** [comment]
On the "Weeks" view
- Hovering on the title e.g. "Customise your home" should have underline

Mosaic animation 
- Going from Years to Months and Months to Weeks, could the images animate, similar to Apple Photos? For example, on a "Months" view, clicking the mosaic, the bigger image would grow into its larger (week view) size.
