### ISSUE TITLE
Footer consistency 

### ISSUE THREAD

**Issue by danieljune** [juneHQ/changelog#29]
To be consistent with june.so

Update

"Set up June" section
Footer font styles
Login button font style in header (not pictured)

![image](https://github.com/juneHQ/changelog/assets/104089773/07895a3a-4654-426e-b0da-970b3710d751)

![image](https://github.com/juneHQ/changelog/assets/104089773/3130edf9-ac86-4c87-a7a4-9048a069951d)

**Comment by jst4cks** [comment]
@ferrucc-io @danieljune this update seems to be directly affected by the themes, can I get an updated version of https://drive.google.com/file/d/1fmd-PJOFknQxDhIxfnaLOjSiz3krc8j2/view?usp=sharing so I can just copy the updated themes?
