### ISSUE TITLE
[Docs] Minor changes suggestion in getting started steps in README to avoid potential bug when starting up

### ISSUE THREAD

**Issue by clairechabas** [juneHQ/changelog#6]
Hi! 
First of all, awesome template thanks for sharing this 🙏

I cloned the repo, installed the dependencies and ran the dev server and the first thing that displayed on the screen was the following error:
 
<img width="1077" alt="Capture d’écran 2023-03-22 à 12 52 37" src="https://user-images.githubusercontent.com/20463332/226899743-69eb545e-7775-4cf4-8bfd-52fd891479b9.png">

Turns out I had forgotten to create a `.env.local` file to enable the environment variables and since they're used in some `<Link>` components it resulted in this error. I thought "my bad" but also that maybe I could suggest a minor change to the README to move this step up and clarify it in the "Getting started" section as it can be forgotten if not specified clearly:

-----

[...] 

## Getting started

The easiest way to try this starter is to run it locally on your computer.

First, you'll need to create your own copy of this starter. You can do so by clicking the ["Use this template"](https://github.com/ferrucc-io/changelog/generate) button on GitHub and filling out the [form](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template).

Once you've cloned the repository, create a `.env.local` file to setup the environment variables, you can reuse the default  variables or change them as you will:

```
cp .env.example .env.local
```

Then install dependencies and start the Next.js server:

[...] 

-----

I didn't know if this repo was open to outside contributions so I didn't create a PR for this but I can open one if you think this small change is relevant 🙃 

PS: Also the "Use this template" link leads to a `404`, it doesn't seem that the repo has been defined as [a template repo](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository) yet.

Anyway thanks again for this starter it's great! 👍

**Comment by ferrucc-io** [comment]
Hey there @clairechabas thanks for reporting these issues! Feel free to open PRs to fix this contributions are super welcome! If you can't I'll push a fix on our end :)

@orliesaurus I just pushed a fix to the template link issue you mentioned and am looking into the markdown fix too 🙌
