### ISSUE TITLE
How do I get the admin panel?

### ISSUE THREAD

**Issue by Maaaz-Shaheen** [juneHQ/changelog#90]
### Discussed in https://github.com/juneHQ/changelog/discussions/89

<div type='discussions-op-text'>

<sup>Originally posted by **Maaaz-Shaheen** September 25, 2024</sup>
The ReadME mentions an `easy to use admin panel` however, I can't find how to enable it or access it in the app? Am I missing something obvious?</div>

**Comment by ferrucc-io** [comment]
Hey there good catch here - unfortunately there's no admin panel - it's just markdown files that get rendered into a static site!
